#!/bin/bash

DJANGODIR=/srv/mode/DigitalMediaPlatform/mobilemode/modetwo # Django project directory
SOCKFILE=/srv/mode/DigitalMediaPlatform/mobilemode/modetwo/modetwo_daphne.sock # we will communicte using this unix socket
DJANGO_SETTINGS_MODULE=modetwo.settings # which settings file should Django use
DJANGO_ASGI_MODULE=modetwo.asgi # ASGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
export HOMEDIR=/home/mode/
cd $HOMEDIR

source .virtualenvs/modetwoenv/bin/activate
#source /usr/local/bin/virtualenvwrapper.sh
#. /webapps/user2/bin/virtualenvwrapper.sh
#workon modetwoenv



cd $DJANGODIR
#export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
#export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec daphne -u $SOCKFILE ${DJANGO_ASGI_MODULE}:channel_layer

