#!/bin/bash
_user="$(id -u -n)"
_group="$(id -g -n)"

NAME="modetwo_app_server" # Name of the application
DJANGODIR=/srv/mode/DigitalMediaPlatform/mobilemode/modetwo # Django project directory
SOCKFILE=/srv/mode/DigitalMediaPlatform/mobilemode/modetwo/gunicorn.sock # we will communicte using this unix socket
USER=$_user # the user to run as
GROUP=$_group # the group to run as
NUM_WORKERS=1 # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=modetwo.settings # which settings file should Django use
DJANGO_WSGI_MODULE=modetwo.wsgi # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
pwd
source /home/mode/.virtualenvs/modetwoenv/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-
~                
